### ISSUE TITLE
Can't retrieve attributes

### ISSUE THREAD

**Issue by ggonmar** [GeorgeSG/ha-slack-user#11]
It may be matter of me not being savvy enough on HA, but I'm trying to get the huddle_state of the entity I'm pulling, to no avail:

From documentation, given the sensor `sensor.slack_g`, there is an attribute called `huddle_state`.

I've set up a template sensor as follows:
```
sensor:
  - platform: template
    sensors:
        slack_huddle:
             value_template: "{{ states_attr('sensor.slack_g', 'huddle_state') }}"
```

But it's showing a permanent "Unavailable.
The same happens with other attributes.
